version: '3'

services:
  api:
    build:
      context: ./src/api/
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./src/api:/usr/src/app
    networks:
      - mynetwork

  streamlit:
    build:
      context: ./src/app-streamlit/
      dockerfile: Dockerfile.streamlit
    depends_on:
      - api
    ports:
      - "8501:8501"
    volumes:
      - ./src/app-streamlit:/usr/src/app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
